server:
  port: 8080   # 设置访问端口
  servlet:
      context-path: /   #设置访问根路径
  mvc:
      date-format: yyyy-MM-dd hh:mm:ss    #设置时间转换格式
spring:
  profiles:
    active: postgres      #设置启动哪一个配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #设置连接池
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    initialization-mode: always


  #    schema:
  #    - classpath:department.sql   #设置初始化脚本名称

  #设置国际化默认文件名
  messages:
    basename: i18n.base   #设置设置国际化文件默认包 文件名
#关闭模板引擎缓存
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#    prefix: classpath:/templates

mybatis:
#  config-location:  classpath:mybatis/config.xml         #指定mybatis默认配置文件 不和configuration 同时使用
  mapper-locations: classpath:mybatis/mapper/*.xml      #设置设置mapper映射文件地址
  type-aliases-package: com.cplh.gt.bean                #设置实体地址com.cplh.gt.bean.
  configuration:
   map-underscore-to-camel-case: true
   cache-enabled: false
#   log-impl: org.apache.ibatis.logging.log4j.Log4jImpl



---

spring:
  profiles: postgres        #设置为文档区设置名称
  datasource:
    username: postgres      #设置数据库连接用户名
    password: root          #设置密码
    url: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false    #设置访问地址
    driver-class-name: org.postgresql.Driver          #设置连接驱动


---
spring:
  profiles: mysql
  datasource:
    validationQuery: SELECT 1 FROM DUAL
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

