server:
  port: 8082   # 设置访问端口
  servlet:
      context-path: /   #设置访问根路径
  mvc:
      date-format: yyyy-MM-dd hh:mm:ss    #设置时间转换格式
spring:
  profiles:
#    active: postgres_test      #设置启动哪一个配置
    active: postgres_dev      #设置启动哪一个配置
  jpa:
   hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
   properties:
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #设置连接池
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙`
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  application:
    name: hystrix-dashboard
#    initialization-mode: always

  #    schema:
  #    - classpath:department.sql   #设置初始化脚本名称

  #设置国际化默认文件名
  messages:
    basename: i18n.base   #设置设置国际化文件默认包 文件名
#关闭模板引擎缓存
  thymeleaf:
    cache: false      #关闭末班引擎的缓存
    mode: HTML5
    encoding: UTF-8   #设置模板引擎编码
  redis:
   database: 0        #设置redis使用的数据库
  # host: 192.168.0.113
   port: 6379         #redis端口
   host: 192.168.7.243    #redis 地址

  output:
    ansi:
      enabled: always       #开启彩色控制台日志
  rabbitmq:
      host: 192.168.7.243
      port: 5672
      username: guest
      password: guest
  mail:
    host: smtp.qq.com
    username: 290965350@qq.com
    password: lhygndwlvkugupbiej    #stmp授权码 邮箱中获取
    properties:
     mail.stmp.ssl.enable: true     #开启ssl验证

#  resources:
#    static-locations: classpath:/META-INF/resources/webjars/**
#    add-mappings: false
#    prefix: classpath:/templates
mybatis:
#  config-location:  classpath:mybatis/config.xml         #指定mybatis默认配置文件 不和configuration 同时使用
  mapper-locations: classpath:mybatis/mapper/*.xml      #设置设置mapper映射文件地址
  type-aliases-package: com.cplh.gt.bean                #设置实体地址com.cplh.gt.bean.
  configuration:
   map-underscore-to-camel-case: true
   cache-enabled: false
banner:
#  image:
##    location: classpath:banner.PNG      #指定banner图片
#    width: 60
#    height: 8
#    invert: false                        #色彩反转
  charset: utf-8                           #编码
  location: classpath:banner.txt            #指定banner文字
debug: true                                 #是否打印详细日志
#   log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

dubbo:
  application:
    name : consum
  registry:
    address: zookeeper://192.168.7.243:2181



---
spring:
  profiles: postgres_dev        #设置为文档区设置名称
  datasource:
    username: postgres      #设置数据库连接用户名
    password: admin          #设置密码
    url: jdbc:postgresql://192.168.100.104:5432/testdb?useSSL=false    #设置访问地址
    driver-class-name: org.postgresql.Driver #设置连接驱动
#    tomcat:
#      validation-query-timeout: 10
---
spring:
  profiles: postgres_test       #设置为文档区设置名称
  datasource:
    username: postgres      #设置数据库连接用户名
    password: admin          #设置密码
    url: jdbc:postgresql://127.0.0.1:5432/testdb?useSSL=false    #设置访问地址
    driver-class-name: org.postgresql.Driver #设置连接驱动
#    tomcat:
#      validation-query-timeout: 10
---
spring:
  profiles: postgres_vm       #设置为文档区设置名称
  datasource:
    username: postgres      #设置数据库连接用户名
    password: admin          #设置密码
    url: jdbc:postgresql://192.168.145.128:5432/xyhdb2?useSSL=false    #设置访问地址
    driver-class-name: org.postgresql.Driver #设置连接驱动
#    tomcat:
#      validation-query-timeout: 10


---
spring:
  profiles: mysql
  datasource:
    validationQuery: SELECT 1 FROM DUAL
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
